# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd6a582e05e162a3983e1c614101063b26db9d63a6c882d81a4acc847c05f3bbe1d5e645730e450049834280d01c28c2589418be1b3a20a036f3c980099e5e7a

test:
  secret_key_base: 8f96888845da7760576534795cd919b1e31ab31bc20244c8c0402a26b6151812bddf99c5882e212bd5d1aec8832b60022db23673134e467b4904ad747daaa2d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
